CREATE LOGIN [test_user]
    WITH PASSWORD = N'zq0aH.vvnH{ci#v:wKaqe&d{msFT7_&#$!~<x|a{zvdF|w|d', SID = 0x6C64231A7FF8A34B9E21D0AAA81EBD0F, DEFAULT_DATABASE = [Abdullin], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

