CREATE TABLE [dbo].[EUCLID 2022_05_17 10_37_52] (
    [column1]  DATETIME2 (7) NOT NULL,
    [column2]  FLOAT (53)    NULL,
    [column3]  FLOAT (53)    NULL,
    [column4]  TINYINT       NULL,
    [column5]  FLOAT (53)    NULL,
    [column6]  FLOAT (53)    NULL,
    [column7]  TINYINT       NULL,
    [column8]  FLOAT (53)    NULL,
    [column9]  FLOAT (53)    NULL,
    [column10] TINYINT       NULL,
    [column11] FLOAT (53)    NULL,
    [column12] FLOAT (53)    NULL,
    [column13] TINYINT       NULL,
    [column14] FLOAT (53)    NULL,
    [column15] FLOAT (53)    NULL,
    [column16] TINYINT       NULL,
    [column17] FLOAT (53)    NULL,
    [column18] FLOAT (53)    NULL,
    [column19] TINYINT       NULL,
    [column20] FLOAT (53)    NULL,
    [column21] FLOAT (53)    NULL,
    [column22] TINYINT       NULL,
    [column23] FLOAT (53)    NULL,
    [column24] FLOAT (53)    NULL,
    [column25] TINYINT       NULL,
    [column26] FLOAT (53)    NOT NULL,
    [column27] INT           NOT NULL,
    [column28] FLOAT (53)    NULL
);

